drop SEQUENCE Relations_seq;
drop SEQUENCE Categories_seq;
drop SEQUENCE CategoriesDes_seq;
drop SEQUENCE Users_seq;
drop SEQUENCE Groups_seq;
drop SEQUENCE GroupsDes_seq;
drop SEQUENCE DataPolicy_seq;
drop SEQUENCE DataPolicyAlias_seq;
drop SEQUENCE Metadata_seq;
drop SEQUENCE HarvestingTask_seq;
drop SEQUENCE HarvestingTaskResult_seq;
drop SEQUENCE HarvestingTaskConfiguration_seq;
drop SEQUENCE DeletedMetadata_seq;


drop table relations;
drop table settings;
drop table sources;
drop table regionsdes;
drop table regions;
drop table operationallowed;
drop table operationsdes;
drop table operations;
drop table metadata;
drop table datapolicyalias;
drop table datapolicy;
drop table deletedmetadata;
drop table usergroups;
drop table users cascade;
drop table groupsdes;
drop table groups cascade;
drop table harvestingtaskresult;
drop table harvestingtaskconfiguration;
drop table harvestingtask;
drop table categoriesdes;
drop table categories;
drop table isolanguagesdes;
drop table isolanguages;
drop table languages;
drop table availability;
