package org.openwis.usermanagement.util;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.UUID;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.openwis.usermanagement.model.user.OpenWISFTP;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Utilities for transform FTP object to String 
 * or String to FTP object. <P>
 */
public final class OpenWISFTPUtils {

   /** The logger */
   private final Logger logger = LoggerFactory.getLogger(OpenWISFTPUtils.class);

   /**
    * Default constructor
    */
   private OpenWISFTPUtils() {

   }

   /**
    * Transform ftp objects to String
    * @param openWISFTPs Open WIS FTP Object list
    * @return ftp The ftp string
    */
   private String toString(List<OpenWISFTP> openWISFTPs) {
      String result = "";
      if (openWISFTPs == null) {
         return result;
      }
      final ByteArrayOutputStream out = new ByteArrayOutputStream();
      final ObjectMapper objectMapper = new ObjectMapper();
      try {
         objectMapper.writeValue(out, openWISFTPs);
         // encode to base64
         result = Base64.getEncoder().encodeToString(out.toByteArray());

      } catch (IOException e) {
         logger.error(e.toString());
      }
      return result;
   }


   private List<OpenWISFTP> fromString(String ftps) {
      //decode to json
      String json = new String(Base64.getDecoder().decode(ftps));
      ObjectMapper mapper = new ObjectMapper();
      try {
         return mapper.readValue(json, new TypeReference<List<OpenWISFTP>>(){});
      } catch (JsonProcessingException e) {
         logger.error(e.toString());
      }
      return new ArrayList<>();
   }

   /**
    * Updates the existing sftps. This method is required because we do not want to replace a password with the mask
    * generated by openwis-portal when sending ftp data to front.
    * @param openWISFTPS
    * @return list of updated sftps
    */
   public static List<OpenWISFTP> updateFTPs(List<OpenWISFTP> oldFtps, List<OpenWISFTP> openWISFTPS) {
      OpenWISFTPUtils openWISFTPUtils = new OpenWISFTPUtils();
      List<OpenWISFTP> ftps = new ArrayList<>();
      for (OpenWISFTP newFtp: openWISFTPS) {
         OpenWISFTP oldFTP = openWISFTPUtils.getFTPByUUID(newFtp.getUuid(),oldFtps);
         if (oldFTP != null) {
             oldFTP.update(newFtp);
            // clone it to avoid shallow copy problems and added to the new list
            ftps.add(oldFTP.clone());
         } else {
            // generate new UUID
            String uuid = UUID.randomUUID().toString();
            OpenWISFTP clone =  newFtp.clone();
            clone.setUuid(uuid);
            ftps.add(clone);
         }
      }
      return ftps;
   }

   private OpenWISFTP getFTPByUUID(String uuid, List<OpenWISFTP> openWISFTPS) {
      if (openWISFTPS == null) {
         return null;
      }
      return openWISFTPS.stream().filter(f -> f.getUuid().equals(uuid)).findFirst().orElse(null);
   }

   /**
    * Transform ftp objects to a json encoded in base64
    * @param openWISFTPs
    * @return json as base64 string
    */
   public static String convertToString(List<OpenWISFTP> openWISFTPs) {
      OpenWISFTPUtils openWISFTPUtils = new OpenWISFTPUtils();
      return openWISFTPUtils.toString(openWISFTPs);
   }

   /**
    * Transform ftp string to ftp objects
    * @param openWISFTPs ftps string
    * @return Open WIS FTP Object list
    */
   public static List<OpenWISFTP> convertToOpenWISFTPs(String openWISFTPs) {
       OpenWISFTPUtils openWISFTPUtils = new OpenWISFTPUtils();
      return openWISFTPUtils.fromString(openWISFTPs);
   }
}
