package org.openwis.metadataportal.services.user.dto;

public enum UserAction {
    ADD,
    CREATE,
    UPDATE,
    REMOVE,
    LOCK,
    UNLOCK,
    REQUEST,
    RECOVER,
    PASSWORD_CHANGE,
    PASSWORD_EXPIRE_NOTIFICATION_MAIL,
    PASSWORD_EXPIRED_NOTIFICATION_MAIL,
    INACTIVITY_NOTIFICATION_MAIL,
    LOGIN, LOGOUT, ACCOUNT_LOCKED_NOTIFICATION_MAIL
}
